### PR TITLE
Split server manager address and display address

### LINKED ISSUE #151: Different display address and manage address
When webgui runs on the same server, ssmgr's manage socket can be access from 127.0.0.1. But because webgui also use this address for display and QR code generate, the config json will be totally wrong. Maybe these two config should be split.

当 Web 界面与服务端跑在相同机器上时，实际上可以用 127.0.0.1 来访问管理端口。但是由于 Web 界面会展示这个连接管理端口的 IP 地址，并用来做二维码生成，所以这里是否应该分开配置管理用 IP 和展示用 IP 呢？

### PR DESCRIPTION
**Pull request by wzxjohn**
close #151

### CODE REVIEW

**Comment by gyteng** [comment]
Change the table of the database will bring some problem of compatibility, when a lower version upgrade to it, the code will not run as well as you expect.

**Comment by wzxjohn** [comment]
Maybe do some migrate job can solve. I think compatibility problem is not big enough to refuse this function.

**Comment by cokebar** [comment]
ssmgr now is changing rapidly. At this stage you'd better do not consider the compatibility, or you'll be stuck.

**Comment by wzxjohn** [comment]
Agree with @cokebar . Compatibility only need to be considered after most features are stable.

**Comment by gyteng** [comment]
I don't think it must be so complicated, just change the host string, eg:

`1.2.3.4` means manage address and display address is same,
`127.0.0.1:1.2.3.4` means `[manage address]:[display address]`

**Comment by wzxjohn** [comment]
It's ok to save 127.0.0.1:1.2.3.4 but a little bit more complicated when config the server. I'll try to implement in this way.

**Comment by wzxjohn** [comment]
After try to store `127.0.0.1:1.2.3.4` in db, I finally find out that store `127.0.0.1:1.2.3.4` is totally not a good idea. Much more codes need to be modified to make sure right address will be used. I'll use my own patched version.

**Pull request closed without merging**
