### PR TITLE
Fix a bug happens when using mysql

### PR DESCRIPTION
**Pull request by viewplatgh**
Fix the error happens when all servers using one single mysql instance

### CODE REVIEW

**Comment by gyteng** [comment]
what error message did you see before?

**Comment by viewplatgh** [comment]
Something like "sumFlow is not in field list"; configure both type s and type m using the same mysql server can reproduce this error.

**Comment by gyteng** [comment]
if type s and type m use the same mysql server, the db name must be
different

2017-04-24 16:15 GMT+08:00 Rob Lao <notifications@github.com>:

**Comment by viewplatgh** [comment]
@gyteng Ok, I didn't see docs about this limit. 
Did you try if using different mysql db name, this error cannot be reproduced? If yes, please ignore this PR.

**Pull request closed without merging**
