### PR TITLE
Enhance the English translation

### PR DESCRIPTION
**Pull request by CicoZhang**
Enhanced some English translation, corrected some translation glitches.

### CODE REVIEW

**Comment by yujincheng08** [comment]
Tansalte 验证码 into captcha should be better.

**Comment by CicoZhang** [comment]
Hi,

"captcha" is something different. I think it means 'SMS check code' here.
Hope this will help.

**Comment by yujincheng08** [comment]
@CicoZhang Hmm, then verification code should be better if this 验证码 is not a turing test.

**Comment by gyteng** [comment]
Thanks for your help.
Please take pull request to dev branch next time.

**Pull request merged**
