### PR TITLE
Add docker compose example for shadowsocks-manager

### PR DESCRIPTION
**Pull request by damonYuan**
Add docker compose example for shadowsocks-manager.

### CODE REVIEW

**Comment by gyteng** [comment]
Your config file is for the old version.

**Comment by damonYuan** [comment]
@gyteng I referred to the document [here](https://github.com/shadowsocks/shadowsocks-manager/wiki/WebGUI), and the docker compose file works perfectly. Could you tell me which part is outdated?

**Comment by damonYuan** [comment]
@gyteng I have updated the container to be able to deploy in swarm mode, please help check. Thx!

**Comment by damonYuan** [comment]
Close because I made one repo for it

> https://github.com/damonYuan/DySocksManager

**Pull request closed without merging**
