### PR TITLE
Try to support ipv6.

### PR DESCRIPTION
**Pull request by yujincheng08**

### CODE REVIEW

**Comment by gyteng** [comment]
There is a tip I have not write on the wiki:

In the web admin page, fill the ip address like `1.1.1.1:2.2.2.2`,
The qrcode in the page will use ip 2.2.2.2
and the m side will communicate s side with ip 1.1.1.1

Do you pr works find with this?

**Comment by yujincheng08** [comment]
@gyteng Yes. I found this but I didn't implement.
Maybe I should keep the compatibility.

**Comment by gyteng** [comment]
Maybe I should change the split char?

**Comment by yujincheng08** [comment]
@gyteng that's a great idea for compatibility. I recommend to use '`,`' as the new split char.

**Comment by yujincheng08** [comment]
@gyteng Updated to support the new split char.

**Comment by yujincheng08** [comment]
Close because incompatibility.

**Pull request closed without merging**
