### PR TITLE
Enable affiliates program in shadowsocks-manager.

### PR DESCRIPTION
**Pull request by kellyxiepei**
Affiliates program workflow:
1. Referrer shares his/her refer link to a new user.
2. The new user clicks the link and a cookie is planted in the new user's browser. User id of the referrer is encoded into the cookie. 
3. The new user register a new account.
4. Shadowsocks manager server decode the cookie and give bonus to the referrer.

Change list:
1. Add a affiliates page for user which show his/her affiliates link and referring history.
2. Add a affiliates setting for admin.
3. Add a affiliates page for admin which show all the referring history.
4. Check fraud reference when sending code and signing up.
5. Give bonus to the referrer after signing up.

### CODE REVIEW

**Comment by gyteng** [comment]
How to prevent someone signup new account for himself?

**Comment by kellyxiepei** [comment]
@gyteng The IP address of the referrer is encoded and encrypted in the share link and in the cookie. When a new user is signing up, the IP address of the new user will be compared with the IP address in the cookie. If the two IP are same, the sign up request will be rejected.

**Comment by gyteng** [comment]
Please add the pull request to dev branch and I will test it later

**Comment by kellyxiepei** [comment]
Sure, I will create a new pull requests.

**Pull request closed without merging**
